# Generated by Django 4.0.3 on 2022-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='reviewed_source_segment',
            new_name='reviewed_source',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='reviewed_target_segment',
            new_name='reviewed_target',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='source_segment',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='target_segment',
            new_name='target',
        ),
        migrations.AddField(
            model_name='segment',
            name='user_edited_target',
            field=models.TextField(blank=True),
        ),
    ]
