# Generated by Django 4.0.3 on 2022-03-04 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_translationquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationquery',
            name='miscellaneous',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translationquery',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='tr', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationquery',
            name='target_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=5),
            preserve_default=False,
        ),
    ]
